### ISSUE TITLE
关于嵌套kv的支持

### ISSUE THREAD

**Issue by jsyishan** [XavierCHN/gulp-dotax#1]
如
```
		// Creature Data
		//----------------------------------------------------------------
		"Creature"
		{
			"ItemDrops"
			{
				"Consumables"
				{
					"Item"
					{
						"1"  			"item_health_potion"
						"2"				"item_health_potion"
						"3"				"item_mana_potion"
						"4"				"item_mana_potion"
						"5"				"item_enchanted_mango"
					}
					"Chance"			"12"
				}
```
这种嵌套的情况是否有办法在xlsx中合理编辑并被正确转译为kv？

[source](https://github.com/SteamDatabase/GameTracking-Dota2/blob/eca58b88615c3306422f2978277335258987b08e/game/dota_addons/dungeon/scripts/npc/npc_units_custom.txt#L84)

**Comment by jsyishan** [comment]
@XavierCHN

**Comment by XavierCHN** [comment]
可以在key中使用[{]和[}]来达成，具体见
https://github.com/XavierCHN/gulp-dotax/blob/master/src/sheetToKV.ts#L124-L132
