### ISSUE TITLE
卡死在txt转js

### ISSUE THREAD

**Issue by DaemonGWW** [XavierCHN/gulp-dotax#4]
![image](https://github.com/XavierCHN/gulp-dotax/assets/63569319/15d4772d-e7eb-4d0c-bf8b-b0d4908b5e1a)

只要只剩下注释就会卡死在txt转js这一步

**Comment by XavierCHN** [comment]
问题已知，但是从目前的状况来看暂时不准备修复
**此问题可以通过避免让文件的最后一行为注释来解决（最后一行多加一个回车）**
具体原因为引用的`easy-keyvalues`的一个BUG
https://github.com/robincodex/easy-keyvalues/blob/master/src/KeyValues.ts#L510

**Comment by XavierCHN** [comment]
fixed in 9a01a3af74c77bac51b552769767f070c4a118bb
