### ISSUE TITLE
Using 'inclues' rather than 'startswith' may introduce more flexibility when transfering sheet to localization

### ISSUE THREAD

**Issue by CyFio** [XavierCHN/gulp-dotax#5]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `gulp-dotax@1.1.17` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/gulp-dotax/lib/sheetToKV.js b/node_modules/gulp-dotax/lib/sheetToKV.js
index 5351968..42c6eac 100644
--- a/node_modules/gulp-dotax/lib/sheetToKV.js
+++ b/node_modules/gulp-dotax/lib/sheetToKV.js
@@ -106,7 +106,7 @@ function sheetToKV(options) {
                 return `${indentStr}"${key}" { "ItemDef" "${cell}" }`;
             }
             // 处理写excel文件中的本地化文本
-            if (key.startsWith(`#Loc`)) {
+            if (key.includes(`#Loc`)) {
                 if (cell == `` || cell == undefined)
                     return;
                 if (cell.trim && cell.trim() == ``)
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

since we never use '#Loc{}' for KV keys,  I think its ok to use inclues() instead of startswith() to support patterns like 'custom_prefix#Loc{}custom_postfix'

**Comment by XavierCHN** [comment]
accepted and fixed in fdd3588c130be7f5f4e2c0dc9e51c8aca06983e7
