### ISSUE TITLE
sheetTokv中193行的判断cell== ``，如果cell值为0会为true，js魅力时刻

### ISSUE THREAD

**Issue by kapaez** [XavierCHN/gulp-dotax#6]
if (abilityValuesBlock && key !== `AbilityValues[{]`) {
                if (cell == `` || cell == undefined)
                    return;

应该是3个等于：
            if (abilityValuesBlock && key !== `AbilityValues[{]`) {
                if (cell === `` || cell == undefined)
                    return;

**Comment by XavierCHN** [comment]
fixed in v1.2.5 cec6a8f702335909626fb6ef5fee2bc16a4a9235
